---
- name: Fetch /etc/os-release
  raw: cat /etc/os-release
  register: os_release
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false

- name: Verify proxmox server should be install python
  raw: which pip
  register: need_bootstrap
  failed_when: false
  changed_when: false
  tags:
    - facts

- include_tasks: prepared.yaml

- include_tasks: provision.yaml
  tags:
    - "created"

- include_tasks: manage.yaml