---
- name: 'Debian install pip packages'
  raw: "apt install {{ packages|join(' ') }}"
  when: '''ID=debian'' in os_release.stdout_lines or ''ID=ubuntu'' in os_release.stdout_lines'

- name: 'Install dependencies'
  pip:
    name: '{{ pip_packages }}'
    extra_args: --user