---
- name: 'Debian install pip packages'
  raw: "apt install {{ packages|join(' ') }}"
  when: '''ID=debian'' in os_release.stdout_lines or ''ID=ubuntu'' in os_release.stdout_lines'
  failed_when: false
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false

- name: 'Install dependencies'
  pip:
    name: '{{ pip_packages }}'
    extra_args: --user